services:
  backend:
    build: ./backend
    ports:
      - "9000:9000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    environment:
      - VITE_BASE_URL=http://backend:9000  # Override for Docker
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules